-- Open Source Legends: Postgres schema.
-- Converted from db/schema.sql (the original Turso/libSQL schema, kept until the
-- cutover is proven) with `npx libsql-pg convert-schema`, then reviewed by hand:
-- the converter (0.1.0) mis-parsed the trailing `-- where the signup came from`
-- comment on the `source` line and emitted the next column as one named "--";
-- the created_at column below is what the SQLite schema meant.
-- Types: INTEGER PRIMARY KEY AUTOINCREMENT -> bigint identity, TEXT -> text,
-- TEXT DEFAULT (datetime('now')) -> timestamptz DEFAULT now().

create table if not exists waitlist (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email text NOT NULL UNIQUE,
  source text NOT NULL DEFAULT 'collect',
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_waitlist_created_at ON waitlist (created_at);
